version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Create virtualenv
          command: |
            python3 -m venv .venv
      - run:
          name: Install requirements
          command: |
            . .venv/bin/activate
            pip install -r requirements.txt
            pip install pytest-coverage flake8 mypy isort
      - run:
          name: Run lints
          command: |
            . .venv/bin/activate
            flake8 .
            isort -rc . --check-only
      - run:
          name: Run static type checker
          command: |
            . .venv/bin/activate
            mypy .
      - run:
          name: Run tests
          command: |
            . .venv/bin/activate
            pytest .

